### ISSUE TITLE
MP3 playback position with TrackBar

### ISSUE THREAD

**Issue by brandy1956** [CHERTS/newac#13]
I have a Delphi application which plays mp3 files using MP3In and AudioOut. I show the progress on a TrackBar but as soon as the mp3 start playing the TrackBar jumps to about 20%. When the TrackBar reaches 100% the file hasn't finished playing.

I set the TrackBar maximum with the following code:

    Bar1.Maximum :=MP3In1.TotalTime/(24*3600);

In the OnProgress event for AudioOut I have the following:

    Bar1.Position := AudioOut1.TimeElapsed/(24*3600);

Any suggestions?

I've attached an image showing the TrackBar as soon as the play starts. It also shows the Time Left has dropped by 36 seconds.

![MP3](https://user-images.githubusercontent.com/92492085/137230278-e4bd7d53-19ef-4ab3-92f7-604097293b9f.jpg)

**Comment by pedrolopix** [comment]
I had this problem and resolved it by converting to milliseconds, like this:

`milliseconds := trunc(FDSAudioOut.Input.Position * FAudioIn.TotalTimeMs / FDSAudioOut.Input.Size);`

**Comment by NoIdeaUsername** [comment]
Thanks a lot! Go to use it

ciao e grazie!
