### ISSUE TITLE
Delphi 11.0 - Installation OK using Rio dpk but not compile in an application

### ISSUE THREAD

**Issue by NoIdeaUsername** [CHERTS/newac#14]
Hi

As in subject, on Delphi 11.0 the library itself install; opening an old project from D10.4 everything ok but doesn't compile because library (ACS_CLASSES).

It seems that the issue is in fastmove

Thanks in advance

have a nice day to all

**Comment by CHERTS** [comment]
Hi, 

I added support RAD Studio 10.4 (Sydney) and RAD Studio 11 (Alexandria)
see commit https://github.com/CHERTS/newac/commit/1155a1bcdddb5150c3253b823f6cd13714572109

Please test Alexandria support.

**Comment by NoIdeaUsername** [comment]
I 

Inviato da iPhone

**Comment by NoIdeaUsername** [comment]
exception

Unable to load project NewAC_Alexandria.dproj
error reading 
NewAC_Alexandria.dproj

Fatal error 250477278. Line271, Column 53
Fatal error 250477278. Line271, Column 53
Fatal error 250477278. Line271, Column 53

**Comment by NoIdeaUsername** [comment]
![image0](https://user-images.githubusercontent.com/11374254/146008494-e791a224-55f7-4168-bc7c-2ba6396ec943.jpeg)

**Comment by NoIdeaUsername** [comment]
Thanks

**Comment by CHERTS** [comment]
Fixed, please check now.

**Comment by NoIdeaUsername** [comment]
Perfect! Compiled and VCL installed.

Thanks thanks
