### ISSUE TITLE
Rio 10.3.2

### ISSUE THREAD

**Issue by NoIdeaUsername** [CHERTS/newac#9]
Hello, Thanks for the code maintenance.
Installed libraries on 10.3.2 using the previous dpk; al is ok. Imported an XE project and the compile result is in an error "E2291 Missing implementation of interface method Istream.seek
Libwma1.pas

I'm not smart enough to correct the code, I apologize for this.

Thanks in advance

**Comment by CHERTS** [comment]
Hi, added RIO support, see commit https://github.com/CHERTS/newac/commit/7430a335e1e242caa58bcbcb2c82bcdc4ec4291c

**Comment by NoIdeaUsername** [comment]
Good morning Mikhail

I apologize for this delayed reply, thanks a lot for the time you spent to solve this issue

best regards
Eugenio
